### ISSUE TITLE
Parsing error 

### ISSUE THREAD

**Issue by tensulin** [vgteam/GetBlunted#55]
Hi I want to use the command on a gfa, however I get the error

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
```

When I use gfalint to check my gfa file it tells me everything is fine. What could be a possible error source?

The link to my gfa:
https://jlubox.uni-giessen.de/getlink/fiWG5ePr17z7x7B6yDcKs2HZ/tag_less_dbg.gfa

Full Verbose log:

```
[get_blunted] Executing command: ./get_blunted -i tag_less_dbg.gfa -V
[get_blunted : 0.0 s elapsed] Reading GFA...
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
Aborted
```

Thank you in advance!

**Comment by jeizenga** [comment]
Your error occurs because your GFA's header line lists its version with the tag `VN:Z:debruijn-rs`. Your tag is well-formed according to the SAM flag semantics, so the fact that GetBlunted crashes with no explanation is definitely a bug. However, this GFA is also breaking conventional expectations of most tools in the field. The `VN` tag is generally used to indicate which version of the [GFA specification](https://github.com/GFA-spec/GFA-spec/tree/9774d44132884d9a019c0f2682cb109be23c2db4?tab=readme-ov-file#gfa-graphical-fragment-assembly-gfa-format-specification) the file conforms to: 1.0, 1.1, or 2.0. Instead, your GFA appears to be listing a software tool that was used to produce the GFA.

Under the hood, what's happening is that one of our internal libraries is attempting to parse `debruijn-rs` as a decimal number. This isn't really correct, because the `Z` is supposed to indicate that the tag is a free-form string, not a number. However, the correct behavior would probably be to crash with an informative message, because the tag is being misused. It could be a bit complicated to implement a fix for this issue on our end since the problem is in a library we depend on, so I don't have a definite timeline for you. The easiest solution would probably be to just correct the tag to `1.0` yourself, which could be easily done with `sed`.

**Comment by tensulin** [comment]
Hi, thank you very much! This resolved my issue. From my side this issue can close. I can also write an issue to the library that you use, so that they can fix it
