### ISSUE TITLE
--input_gfa required

### ISSUE THREAD

**Issue by gorkemsolun** [vgteam/GetBlunted#56]
The output of the --help command does not align with the information provided in the readme @jeizenga @rlorigro 

![image](https://github.com/user-attachments/assets/7c8534cd-a01b-4cc8-9a01-db306a43f548)

**Comment by jeizenga** [comment]
Thanks for the pointer. I've corrected the example in the README.

**Comment by gorkemsolun** [comment]
@jeizenga It also gave an error

**Comment by jeizenga** [comment]
Are you able to share your input?

**Comment by gorkemsolun** [comment]
@jeizenga https://drive.google.com/file/d/1or2qz0jMy2nwllYCnH6tRMJ7_8boQU5v/view?usp=drive_link

**Comment by jeizenga** [comment]
The issue is that your GFA has the carriage return character added to the end of lines, which is probably the result of having been edited in a Windows text editor (see e.g. [here](https://stackoverflow.com/questions/7013034/does-windows-carriage-return-r-n-consist-of-two-characters-or-one-character) for more on this). You should be able to remove the carriage returns using `tr -d '\r' < input.gfa > fixed.gfa`. However, from my cursory look at this GFA, it appears that it is already a blunt-ended graph, so it's not really necessary to use `GetBlunted` on it.

**Comment by gorkemsolun** [comment]
@jeizenga Thanks!
